'use client';

import React, { useState } from 'react';
import {
  Grid,
  Column,
  Tile,
  Button,
  TextInput,
  Select,
  SelectItem,
  Toggle,
  Section,
  Heading,
  ClickableTile,
} from '@carbon/react';
import { Send, Chat, Renew } from '@carbon/icons-react';
import { useTranslation } from '@/lib/i18n/context';

interface Message {
  id: number;
  role: 'user' | 'assistant';
  text: string;
  timestamp: string;
}

const initialMessages: Message[] = [
  {
    id: 1,
    role: 'user',
    text: 'What are the top performing content topics for our brand this quarter?',
    timestamp: '10:23 AM',
  },
  {
    id: 2,
    role: 'assistant',
    text: 'Based on your GEO analytics, the top 3 performing topics this quarter are:\n\n1. **AI Content Optimization** — 34% engagement increase, 12.4K avg. search volume\n2. **Enterprise SEO Automation** — 28% engagement increase, 8.2K avg. search volume\n3. **Brand Voice Consistency** — 22% engagement increase, 5.1K avg. search volume\n\nI recommend doubling down on AI Content Optimization since it aligns with rising search trends and your brand authority score of 92 in that cluster.',
    timestamp: '10:23 AM',
  },
  {
    id: 3,
    role: 'user',
    text: 'Can you draft an outline for a blog post about AI content optimization best practices?',
    timestamp: '10:25 AM',
  },
  {
    id: 4,
    role: 'assistant',
    text: 'Here is a suggested outline for "AI Content Optimization Best Practices in 2026":\n\n**Introduction** — The shift from traditional SEO to GEO\n\n**Section 1: Understanding Generative Engine Optimization**\n- What GEO means for content creators\n- Key differences from traditional SEO\n\n**Section 2: Data-Driven Content Strategy**\n- Leveraging semantic topic maps\n- Keyword authority and cluster analysis\n\n**Section 3: AI-Assisted Content Creation**\n- Setting up brand voice guardrails\n- Balancing automation with human expertise\n\n**Section 4: Measurement and Iteration**\n- GEO score tracking\n- Competitor benchmarking\n\n**Conclusion** — The future of AI-optimized content\n\nWant me to flesh out any section in detail?',
    timestamp: '10:25 AM',
  },
];

const recentConversations = [
  { id: 1, title: 'Content strategy Q1 review', date: 'Today' },
  { id: 2, title: 'Competitor gap analysis', date: 'Yesterday' },
  { id: 3, title: 'Blog outline: GEO trends', date: 'Feb 17' },
  { id: 4, title: 'Social media calendar planning', date: 'Feb 15' },
  { id: 5, title: 'Keyword research for product launch', date: 'Feb 14' },
];

export default function CopilotPage() {
  const { t } = useTranslation();
  const [messages, setMessages] = useState<Message[]>(initialMessages);
  const [inputValue, setInputValue] = useState('');
  const [brandVoice, setBrandVoice] = useState(true);

  const handleSend = () => {
    if (!inputValue.trim()) return;

    const newUserMsg: Message = {
      id: messages.length + 1,
      role: 'user',
      text: inputValue,
      timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
    };

    const newAssistantMsg: Message = {
      id: messages.length + 2,
      role: 'assistant',
      text: 'I am processing your request. This is a mock response — in production, this would be generated by the selected AI model with your chosen context and brand voice settings applied.',
      timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
    };

    setMessages((prev) => [...prev, newUserMsg, newAssistantMsg]);
    setInputValue('');
  };

  return (
    <div style={{ padding: '2rem' }}>
      <Section level={1}>
        <Heading style={{ marginBottom: '0.5rem' }}>
          {t('AI Chat Co-pilot')}
        </Heading>
        <p style={{ color: 'var(--cds-text-secondary)', marginBottom: '2rem' }}>
          {t('Your intelligent assistant for content strategy, SEO insights, and creative ideation.')}
        </p>
      </Section>

      <Grid narrow>
        {/* Chat Panel */}
        <Column lg={10} md={5} sm={4}>
          <Tile
            style={{
              height: '600px',
              display: 'flex',
              flexDirection: 'column',
              padding: 0,
              overflow: 'hidden',
            }}
          >
            {/* Messages */}
            <div
              style={{
                flex: 1,
                overflowY: 'auto',
                padding: '1.5rem',
                display: 'flex',
                flexDirection: 'column',
                gap: '1rem',
              }}
            >
              {messages.map((msg) => (
                <div
                  key={msg.id}
                  style={{
                    display: 'flex',
                    justifyContent: msg.role === 'user' ? 'flex-end' : 'flex-start',
                  }}
                >
                  <div
                    style={{
                      maxWidth: '75%',
                      padding: '0.75rem 1rem',
                      borderRadius: '0.5rem',
                      backgroundColor:
                        msg.role === 'user'
                          ? 'var(--cds-interactive)'
                          : 'var(--cds-layer-02)',
                      color:
                        msg.role === 'user'
                          ? 'var(--cds-text-on-color)'
                          : 'var(--cds-text-primary)',
                    }}
                  >
                    <p style={{ fontSize: '0.875rem', whiteSpace: 'pre-wrap', lineHeight: '1.5' }}>
                      {msg.text}
                    </p>
                    <p
                      style={{
                        fontSize: '0.6875rem',
                        marginTop: '0.5rem',
                        opacity: 0.7,
                      }}
                    >
                      {msg.timestamp}
                    </p>
                  </div>
                </div>
              ))}
            </div>

            {/* Input */}
            <div
              style={{
                display: 'flex',
                gap: '0.5rem',
                padding: '1rem 1.5rem',
                borderTop: '1px solid var(--cds-border-subtle)',
                alignItems: 'flex-end',
              }}
            >
              <div style={{ flex: 1 }}>
                <TextInput
                  id="chat-input"
                  labelText=""
                  hideLabel
                  placeholder={t('Ask the AI co-pilot anything...')}
                  value={inputValue}
                  onChange={(e) => setInputValue(e.target.value)}
                  onKeyDown={(e) => {
                    if (e.key === 'Enter') handleSend();
                  }}
                />
              </div>
              <Button
                renderIcon={Send}
                iconDescription={t('Send')}
                hasIconOnly
                kind="primary"
                onClick={handleSend}
              />
            </div>
          </Tile>
        </Column>

        {/* Side Panel */}
        <Column lg={6} md={3} sm={4}>
          <Tile style={{ marginBottom: '1rem' }}>
            <h4 style={{ fontSize: '0.9375rem', fontWeight: 600, marginBottom: '1rem' }}>
              {t('Co-pilot Settings')}
            </h4>

            <div style={{ marginBottom: '1.25rem' }}>
              <Select
                id="ai-model"
                labelText={t('AI Model')}
                defaultValue="claude"
              >
                <SelectItem value="claude" text="Claude (Opus 4)" />
                <SelectItem value="gemini" text="Gemini 2.5 Pro" />
                <SelectItem value="granite" text="IBM Granite 3.2" />
              </Select>
            </div>

            <div style={{ marginBottom: '1.25rem' }}>
              <Select
                id="context-mode"
                labelText={t('Context')}
                defaultValue="content"
              >
                <SelectItem value="content" text="Content" />
                <SelectItem value="seo" text="SEO" />
                <SelectItem value="strategy" text="Strategy" />
              </Select>
            </div>

            <div>
              <Toggle
                id="brand-voice-toggle"
                labelText={t('Brand Voice')}
                labelA={t('Off')}
                labelB={t('On')}
                toggled={brandVoice}
                onToggle={(checked) => setBrandVoice(checked)}
              />
            </div>
          </Tile>

          <Tile>
            <h4 style={{ fontSize: '0.9375rem', fontWeight: 600, marginBottom: '1rem' }}>
              {t('Recent Conversations')}
            </h4>
            <div style={{ display: 'flex', flexDirection: 'column', gap: '0.25rem' }}>
              {recentConversations.map((conv) => (
                <ClickableTile
                  key={conv.id}
                  style={{ padding: '0.75rem' }}
                >
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                      <Chat size={16} />
                      <span style={{ fontSize: '0.875rem' }}>{conv.title}</span>
                    </div>
                    <span style={{ fontSize: '0.75rem', color: 'var(--cds-text-secondary)' }}>
                      {conv.date}
                    </span>
                  </div>
                </ClickableTile>
              ))}
            </div>
          </Tile>
        </Column>
      </Grid>
    </div>
  );
}
